// <auto-generated />
namespace RapidSale.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_slider_Alter_Experience_add_img : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_slider_Alter_Experience_add_img));
        
        string IMigrationMetadata.Id
        {
            get { return "202101290530363_Add_slider_Alter_Experience_add_img"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
